coffeedapp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'coffeedapp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    (r'', include('core.urls')),
)

core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
import core.views as coreviews

urlpatterns = patterns('',

    url(r'^$', coreviews.LandingView.as_view()),
    url(r'location/$', coreviews.LocationListView.as_view()),
    url(r'location/(?P<pk>\d+)/detail/$', coreviews.LocationDetailView.as_view(), name='location_detail'),
    url(r'location/(?P<pk>\d+)/detail/location/undefined/detail/$', coreviews.LocationDetailView.as_view(), name='location_detail'),
    url(r'search/$', coreviews.SearchListView.as_view()),
    url(r'location/create/$', login_required(coreviews.LocationCreateView.as_view())),
    url(r'location/(?P<pk>\d+)/update/$', login_required(coreviews.LocationUpdateView.as_view()), name='location_update'),
    url(r'location/(?P<pk>\d+)/review/create/$', login_required(coreviews.ReviewCreateView.as_view()), name='review_create'),
    url(r'location/(?P<pk>\d+)/review/update/$', login_required(coreviews.ReviewUpdateView.as_view()), name='review_update'),
    url(r'entrance/$', coreviews.entrance),
)

core/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db.models import Avg
from geoposition.fields import GeopositionField

import os
import uuid

def upload_to_location(instance, filename):
    blocks = filename.split('.')
    ext = blocks[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    instance.title = blocks[0]
    return os.path.join('uploads/', filename)

RATING_CHOICES = (
    (0, 'None'),
    (1, '*'),
    (2, '**'),
    (3, '***'),
    (4, '****'),
    (5, '*****'),
    )

YESNO_CHOICES = (
 (0, 'No'),
 (1, 'Yes')
 )

PLURAL_CHOICES = (
 (0, 'None'),
 (1, 'Minimal'),
 (2, 'Some'),
 (3, 'Ample')
 )

WIFI_CHOICES = (
 (0, 'None'),
 (1, 'Spotty'),
 (2, 'Strong')
 )

GYM_CHOICES = (
 (0, 'None'),
 (1, 'Fitness Center'),
 (2, 'Hardcore Gym Yeah Baby'),
 (3, 'Bodybuilding'),
 (4, 'Garage Gym'),
 (5, 'Powerlifting Gym'),
 (6, 'You cant be serious'),
 )




# Create your models here.

class Location(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField(null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    hours = models.TextField(null=True, blank=True)
    wifi = models.IntegerField(choices=WIFI_CHOICES, null=True, blank=True)
    seating = models.IntegerField(choices=PLURAL_CHOICES, null=True, blank=True)
    outlets = models.IntegerField(choices=PLURAL_CHOICES, null=True, blank=True)
    bathrooms = models.IntegerField(choices=YESNO_CHOICES, null=True, blank=True)
    gymtype = models.IntegerField(choices=GYM_CHOICES, null=True, blank=True)
    proshop = models.IntegerField(choices=YESNO_CHOICES, null=True, blank=True)
    outdoor = models.IntegerField(choices=YESNO_CHOICES, null=True, blank=True)
    food = models.IntegerField(choices=YESNO_CHOICES, null=True, blank=True)
    image_file = models.ImageField(upload_to=upload_to_location, null=True, blank=True)
    position = GeopositionField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
         return self.title

    def get_absolute_url(self):
     return reverse(viewname="location_detail", args=[self.id])

    def get_average_rating(self):
        average = self.review_set.all().aggregate(Avg('rating'))['rating__avg']
        if average == None:
            return average
        else:
            return int(average)

    def get_reviews(self):
            return self.review_set.all()

class Review(models.Model):
    location = models.ForeignKey(Location)
    user = models.ForeignKey(User)
    description = models.TextField(null=True, blank=True)
    rating = models.IntegerField(choices=RATING_CHOICES, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)



    

core/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
import core.models as coremodels
from sitegate.decorators import redirect_signedin, sitegate_view

# Create your views here.

class LandingView(TemplateView):
    template_name = 'base/index.html'


class LocationListView(ListView):
    model = coremodels.Location
    template_name = 'location/list.html'
    paginate_by = 50

class SearchListView(LocationListView):

    def get_queryset(self):
        incoming_query_string = self.request.GET.get('query', '')
        return coremodels.Location.objects.filter(address__icontains=incoming_query_string)

class LocationDetailView(DetailView):
    model = coremodels.Location
    template_name = 'location/detail.html'
    context_object_name = 'location'

    def get_context_data(self, **kwargs):
        context = super(LocationDetailView, self).get_context_data(**kwargs)
        location = coremodels.Location.objects.get(id=self.kwargs['pk'])
        if self.request.user.is_authenticated():
            user_reviews = coremodels.Review.objects.filter(location=location, user=self.request.user)
            if user_reviews.count() > 0:
                context['user_review'] = user_reviews[0]
            else:
                context['user_review'] = None
        return context

class LocationCreateView(CreateView):
    model = coremodels.Location
    template_name = 'base/form.html'
    fields =['title', 'description', 'address', 'hours', 'wifi', 'seating', 'outlets', 'bathrooms', 'gymtype', 'proshop', 'outdoor','food', 'image_file', 'position']

class LocationUpdateView(UpdateView):
    model = coremodels.Location
    template_name = 'base/form.html'
    fields =['title', 'description', 'address', 'hours', 'wifi', 'seating', 'outlets', 'bathrooms', 'gymtype', 'proshop', 'outdoor','food', 'image_file', 'position']

class ReviewCreateView(CreateView):
    model = coremodels.Review
    template_name = 'base/form.html'
    fields =['description', 'rating']

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.location = coremodels.Location.objects.get(id=self.kwargs['pk'])
        return super(ReviewCreateView, self).form_valid(form)

    def get_success_url(self):
        return self.object.location.get_absolute_url()



class ReviewUpdateView(UpdateView):
    model = coremodels.Review
    template_name = 'base/form.html'
    fields =['description', 'rating']

    def get_object(self):
        return coremodels.Review.objects.get(location__id=self.kwargs['pk'], user=self.request.user)

    def get_success_url(self):
        return self.object.location.get_absolute_url()

@sitegate_view(widget_attrs={'class': 'form-control', 'placeholder': lambda f: f.label}, template='form_bootstrap3')  # This also prevents logged in users from accessing our sign in/sign up page.
def entrance(request):
    return render(request, 'base/entrance.html', {'title': 'Sign in & Sign up'})

templates/base/entrance.html
{% extends "base/theme.html" %}
{% load sitegate %}
{% block main_content %}

<section id="services">
 <div class="container">
   <div class="row ">
     <div class="col-lg-4 text-center">
      <div class="my_signin_block">
      	<br>
      	<br>
        <br>
        <br>
        <br>
         <h2 class="section-heading"><a href="{{ location.get_absolute_url }}">Sign In</a></h2>
         <h3 class="section-subheading text-muted">Welcome back!</h3>
 {% sitegate_signin_form %}
       </div>
      </div>
<div class="col-lg-4 text-center">
</div>
    <div class="col-lg-4 text-center">
     <div class="my_signup_block">
     	  <br>
      	<br>
      	<br>
        <br>
        <br>
       <h2 class="section-heading"><a href="{{ location.get_absolute_url }}">Join</a></h2>
        <h3 class="section-subheading text-muted">Visit gyms, and provide a review!</h3>
 {% sitegate_signup_form %}
     </div>
    </div>
   </div>
  </div>

</section>

{% endblock %}

templates/base/form.html
{% extends "base/theme.html" %}
{% load widget_tweaks %}
{% block main_content %}
 <div class="header-buffer">
 </div>
 <section id="services">
 <div class="container">
<div class="row">
 {% if form %}
 <div class="col-md-12">
 <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}{{ form.media }}
 {% for field in form %}
 <div class="form-group warning">
 <label for="exampleInputFile">{{ field.label }}</label>
 {{ field|add_class:"form-control"}}
 {% if field.help_text %}<p class="help-block">{{ field.help_text }}</p>{% endif %}
 </div>
 {% if field.errors %}
 {% for error in field.errors %}
 <div class="alert alert-danger" id="error_{{ field.name }}">{{ error|escape }}</div>
 {% endfor %}
 {% endif %}

 {% endfor %}
 <input type="submit" class="btn btn-success" role="button" value="{{ verb|default:"Submit" }}" />
 </form>
</div>
{% endif %}
</div>
</div>
</section>
{% endblock %}

templates/base/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Barbellreview.com</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
   <link href="{% static "css/agency.css" %}" rel="stylesheet">
   <link href="{% static "css/custom.css" %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" class="index">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top navbar-shrink">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="/">Barbellreview.com</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    {% block navigation %}
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services">How It Works</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#team">Our Team</a>
                    </li>
                    <li>
                        <a href="location/">Find a Gym</a>
                    </li>
                    {% endblock %}
                </ul>
                {% block search %}
                {% endblock %}
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    {% block main_content %}
    <!-- Header -->
    <header>
        <div class="container">
            <div class="intro-text">
                <div class="intro-heading"></div>
                <div class="intro-lead-in" style="color:#fff;text-shadow:4px 4px 4px #000;">YOUR REVIEW MATTERS</div>

                <a href="location/" class="page-scroll btn btn-xl">Find a Gym</a>
<br />
<br />
{% block buttoncreateorlogin %}

 {% if user.is_authenticated %}
 <a class="page-scroll btn btn-xl" href="/location/create/">Add a Gym</a> 
 {% else %}
 <a class="page-scroll btn btn-xl" href="/entrance/">Log In / Sign-Up</a>
 {% endif %} 
{% endblock %}

            </div>
        </div>
    </header>
    

    <!-- Services Section -->
    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">How It Works</h2>
                </div>
            </div>
            <div class="row text-center">
                <div class="col-md-4">
                    <img class="coffeed-svg-icon" src="{% static "img/svg/python_flag.svg" %}"></>
                    <h4 class="service-heading">Discover Gyms and clubs that meet your needs</h4>
                    <p class="text-muted">Barbellreview.com allows anyone to proivde their opinion on a gym, fitness center or even a small garage gym.</p>
                </div>
                <div class="col-md-4">
                    <img class="coffeed-svg-icon" src="{% static "img/svg/python_badge.svg" %}"></>
                    <h4 class="service-heading">Review Your Favorites</h4>
                    <p class="text-muted">Find out what other people are saying and chime in with your opinion. Help each other find the best work locale.</p>
                </div>
                <div class="col-md-4">
                    <img class="coffeed-svg-icon" src="{% static "img/svg/python_rocket.svg" %}"></>
                    <h4 class="service-heading">Promote Your Facility</h4>
                    <p class="text-muted">Anyone can add their gym location to barbellreview.com for free. Sit back, relax & watch the read the reviews.</p>
                </div>
            </div>
        </div>
    </section>


    <!-- Team Section -->
    <section id="team" class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Our Team</h2>
                    <h3 class="section-subheading text-muted">Working hard to find you the best of the best.</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <div class="team-member">
                        <img src="{% static "img/team/1.jpg" %}" class="img-responsive img-circle" alt="">
                        <h4>Blaine Stussy</h4>
                        <p class="text-muted">Founder & Designer</p>
                        <ul class="list-inline social-buttons">
                            <li><a href="#"><i class="fa fa-twitter"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-instagram"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </section>
                    </div>
            </div>
        </div>
    </section>
    {% endblock %}

    <footer>
        <div class="container">
            {% block pagination %}
            {% endblock %}
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; barbellreview.com 2015</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Get In Touch</a>
                        </li>
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static "js/jquery.js" %}"></script>
    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="{% static "js/gmaps.js" %}"></script>
    <script src="{% static "js/maps.js" %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "js/bootstrap.min.js"%}"></script>

    <!-- Plugin JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>


    <!-- Custom Theme JavaScript -->
    <script src="{% static "js/agency.js"%}"></script>

</body>

</html>

templates/base/rating.html
<div class="coffeed-rating">
{% if rating == 1 %}
<i class="fa fa-star"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i>
{% elif rating == 2 %}
<i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i>
{% elif rating == 3 %}
<i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i>
{% elif rating == 4 %}
<i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-o"></i>
{% elif rating == 5 %}
<i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i>
{% else %}
<i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i>
{% endif %}
</div>

templates/base/review.html
<div class="row">
 <div class="col-md-8">


  <strong>  {{ review.user.get_full_name }}

 	<a class="subheading"> | {{ review.created_at | date }}</a></strong>
 </div>
 <div class="col-md-4 text-right">
 <h4>{% include 'base/rating.html' with rating=review.rating %}</h4>
 </div>
 
</div>
<p>{{ review.description }}</p>

templates/base/theme.html
{% extends "base/index.html" %}

{% block navigation %}
 <li>
 <a class="page-scroll" href="/location">Find a Gym</a>
 </li>
 {% if user.is_authenticated %}
 <li>
 <a class="page-scroll" href="/location/create/">Add a Gym</a>
 </li> 
 {% else %}
 <li>
 <a class="page-scroll" href="/entrance/">Log In</a>
 </li> 
 {% endif %} 
{% endblock %}

{% block search %}
<form action="/search/" class="navbar-form navbar-right" method="get">
 <div class="form-group">
 <input type="text" placeholder="City or Zip or State" class="form-control" name="query"></input>
 </div>
</form>
{% endblock %}

{% block main_content %}

{% endblock %}

templates/location/detail.html
{% extends "base/theme.html" %}
{% block scripts %}
<script src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script src="{{ STATIC_URL }}theme/js/gmaps.js"></script>
<script src="{{ STATIC_URL }}theme/js/maps.js"></script>
{% endblock %}
{% block main_content %}
<div class="data-layer">
    <ul>
        <li class="location-data" data-latitude="{{ location.position.latitude }}" data-longitude="{{ location.position.longitude }}">{{ location.title }}</li>
    </ul>
</div>
<div class="header-buffer">
</div>
<!-- Services Section -->
<section id="services">
    <div class="container">
        <div class="" >
            <div id="details">
<div class="col-md-12">
<div class="row">
                            <div class="col-md-8">
                            <h2>{{ location.title }}</h2>
                            </div>
                            <div class="col-md-4 text-right">
                            <h2>{% include 'base/rating.html' with rating=location.get_average_rating %}</h2>
                            </div>


                            </div>

                <div class="col-md-8">
                    <div class="row">
                            {% if location.image_file %}
                        <div class="col-md-12" >
                        
                        <img src="{{ location.image_file.url }}" class="img-responsive img-centered full-width" alt="">

                      </div>
                      {% endif %}
                  
                  <div class="row">
                    <div class="col-md-12" >{% include 'location/specifics.html' with location=location %}
                    </div>
                </div>
        <div class="row">
            <div class="col-md-12">
                <p class="">{{ location.description}}</p>
                        <div class="">
                            {% if user.is_authenticated %}
                            <a type="button" href="{% url 'location_update' pk=location.id %}" class="btn btn-default pull-right">Edit Gym Info</a>{% endif %}
                            
                           
                            <br />
                <div class="col-md-12">
                    <hr>
                {% for review in location.get_reviews %}
                {% include 'base/review.html' with location=location %}

                {% endfor %}
                </div>
                        </div>

            </div>
        </div>
        </div>
            </div>
            
            <div class="col-md-4 panel">
                <div class="wide-map short-map" id="map"></div>
                <div class="col-md-3"></div>
                <div class="col-md-6 text-center">
                <br>
                    {% if location.address %}<p>{{ location.address }}</p>{% endif %}
                    {% if location.phone %}<p>{{ location.phone }}</p>{% endif %}
                    {% if location.website %}<p><a href="{{ location.website }}">{{ location.website }}</a></p>
                    {% endif %}
                </div>
            </div>
            </div>
        </div>

    </div>
    <hr>
    <div id="reviews">
            <div class="col-md-8">
             
                   {% if user_review %}
              <div class="bg-warning" style="padding: 15px;">     
                   <h5>Your Review</h5>
                   {% with user_review as review %}
                <div>
                   {% include 'base/review.html' %}
                </div>
                   {% endwith %}
                   {% endif %}
                   {% for review in reviews %}
                   {% include 'base/review.html' %}
                <hr>
                </div>
                   {% endfor %}
               
            </div>
                <div class="col-md-12">
     
    <hr>
                {% if user.is_authenticated %}
                        {% if user_review %}
                        <a type="button" href="{% url 'review_update' pk=location.id %}" class="btn btn-default pull-right">Update Review</a>
                        {% else %}
                        <a type="button" href="{% url 'review_create' pk=location.id %}" class="btn btn-default pull-right">Add Your Review</a>
                        {% endif %}
                {% endif %}

        <div>
        </div>
    </div>


</div>

</section>
{% endblock %}

templates/location/list.html
{% extends "base/theme.html" %}
{% load bootstrap_pagination %}
{% block main_content %}
<div class="data-layer">
    <ul>
    {% for location in object_list %}
        <li class="location-data" data-latitude="{{ location.position.latitude }}" data-longitude="{{ location.position.longitude }}" data-id="{{ location.id }}">{{ location.title }}</li>
    {% endfor %}
    </ul>
</div>
<div id="map" class="wide-map"></div>
<div class="row main-content">
    <div class="col-md-2"></div>
    <div class="col-md-8">
    {% for location in object_list %}
        <div class='row'>
        <div class="col-md-8">
            <h3><a href="{{ location.get_absolute_url }}">{{ location.title }}</a></h3>
        </div>
        <div class="col-md-4 text-right">
            <h3>{% include 'base/rating.html' with rating=location.get_average_rating %}</h3>
        </div>
        <div class="col-md-8">
        {% if location.address %}<p><b>Location:&nbsp;</b>{{ location.address }}</b></p>{% endif %}
        {% if location.hours %}<p>{{ location.hours }}</p>{% endif %}
        {% if location.image_file %}
            <img class="img-responsive" src="{{ location.image_file.url }}"></img>
        {% endif %}
        {% include 'location/specifics.html' with location=location %}
        <p>{{ location.description }}</p>
    </div>
    </div>
    {% endfor %}
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

{% block pagination %}
    {% bootstrap_paginate page_obj range=10 show_prev_next="false" show_first_last="true" %}
{% endblock %}

templates/location/specifics.html
<div class="row">
<div class="col-md-4">
 
<p><b>WIFI: </b>{% if location.wifi %}{{ location.get_wifi_display }}{% else %}----{% endif %}</p>
<p><b>Seating: </b>{% if location.seating %}{{ location.get_seating_display }}{% else %}----{% endif %}</p>
<p><b>Outlets: </b>{% if location.outlets %}{{ location.get_outlets_display }}{% else %}----{% endif %}</p>
<p><b>Bathrooms: </b>{% if location.bathrooms %}{{ location.get_bathrooms_display }}{% else %}----{% endif %}</p>
</div>
<div class="col-md-4">
<p><b>Gym Type: </b>{% if location.gymtype %}{{ location.get_gymtype_display }}{% else %}----{% endif %}</p>
<p><b>ProShop: </b>{% if location.proshop %}{{ location.get_proshop_display }}{% else %}----{% endif %}</p>
<p><b>Outdoor Area: </b>{% if location.outdoor %}{{ location.get_outdoor_display }}{% else %}----{% endif %}</p>
<p><b>Food: </b>{% if location.food %}{{ location.get_food_display }}{% else %}----{% endif %}</p>
</div>
</div>